---
title: "problem_set_5"
output: html_document
---

1. Price Histograms with Facet and Color
# Create a histogram of diamond prices.
# Facet the histogram by diamond color
# and use cut to color the histogram bars.

# The plot should look something like this.
# http://i.imgur.com/b5xyrOu.jpg

# Note: In the link, a color palette of type
# 'qual' was used to color the histogram using
# scale_fill_brewer(type = 'qual')
```{R}
ggplot(aes(x= log(price)), data= diamonds) + 
  geom_histogram(aes(fill = cut)) + 
  facet_wrap(facets= 'color')
```

3. Price vs. Table Colored by Cut
# Create a scatterplot of diamond price vs.
# table and color the points by the cut of
# the diamond.

# The plot should look something like this.
# http://i.imgur.com/rQF9jQr.jpg

# Note: In the link, a color palette of type
# 'qual' was used to color the scatterplot using
# scale_color_brewer(type = 'qual')
```{R}
ggplot(aes(x=table, y=price), data= diamonds) + 
  geom_point(aes(color = cut), alpha = 0.3) + 
  scale_color_brewer(type = 'qual')
```

4. Price vs. Volume and Diamond Clarity
# Create a scatterplot of diamond price vs.
# volume (x * y * z) and color the points by
# the clarity of diamonds. Use scale on the y-axis
# to take the log10 of price. You should also
# omit the top 1% of diamond volumes from the plot.

# Note: Volume is a very rough approximation of
# a diamond's actual volume.

# The plot should look something like this.
# http://i.imgur.com/excUpea.jpg

# Note: In the link, a color palette of type
# 'div' was used to color the scatterplot using
# scale_color_brewer(type = 'div')
```{R}
diamonds2 = transform(diamonds, volume = x*y*z)

ggplot(aes(x=volume, y=price), data = subset(diamonds2, percent_rank(volume) < 0.99)) + 
  geom_point(aes(color = clarity)) + 
  scale_y_log10() + 
  scale_color_brewer(type = 'div')
```

5. Proportion of Friendships Initiated
# Many interesting variables are derived from two or more others.
# For example, we might wonder how much of a person's network on
# a service like Facebook the user actively initiated. Two users
# with the same degree (or number of friends) might be very
# different if one initiated most of those connections on the
# service, while the other initiated very few. So it could be
# useful to consider this proportion of existing friendships that
# the user initiated. This might be a good predictor of how active
# a user is compared with their peers, or other traits, such as
# personality (i.e., is this person an extrovert?).

# Your task is to create a new variable called 'prop_initiated'
# in the Pseudo-Facebook data set. The variable should contain
# the proportion of friendships that the user initiated.
```{R}
pf <- read.delim('/Users/markmeleka/Documents/Comp\ Sci\ and\ Programming\ Learning/Udacity/DAND/Exploratory_Data_Analysis/eda-course-materials/lesson3/pseudo_facebook.tsv')

pf <- transform(pf, prop_initiated = friendships_initiated/friend_count)
```

6. prop_initiated vs. tenure
# Create a line graph of the median proportion of
# friendships initiated ('prop_initiated') vs.
# tenure and color the line segment by
# year_joined.bucket.

# Recall, we created year_joined.bucket in Lesson 5
# by first creating year_joined from the variable tenure.
# Then, we used the cut function on year_joined to create
# four bins or cohorts of users.

# (2004, 2009]
# (2009, 2011]
# (2011, 2012]
# (2012, 2014]

# The plot should look something like this.
# http://i.imgur.com/vNjPtDh.jpg
# OR this
# http://i.imgur.com/IBN1ufQ.jpg
```{R}
pf <- transform(pf, year_joined = floor(2014-tenure/365))
pf <- transform(pf, year_joined.bucket = cut(pf$year_joined, c(2004,2009,2011,2012,2014)))

ggplot(aes(x=tenure, y=prop_initiated), data=pf) + 
  geom_line(aes(color=year_joined.bucket), 
            stat='summary',
            fun.y = median)
```

7. Smoothing prop_initiated vs. tenure
# Smooth the last plot you created of
# of prop_initiated vs tenure colored by
# year_joined.bucket. You can bin together ranges
# of tenure or add a smoother to the plot.
```{R}
ggplot(aes(x=tenure, y=prop_initiated), data=pf) + 
  geom_line(aes(color=year_joined.bucket), 
            stat='summary',
            fun.y = median) + 
  geom_smooth()
```

9. For the group with the largest proportion of friendships, what is the mean proportion of friendships initiated?
```{R}
with(subset(subset(pf, year_joined.bucket == '(2012,2014]'), !is.na(prop_initiated)), mean(prop_initiated))
```

10. Price/Carat Binned, Faceted, & Colored
# Create a scatter plot of the price/carat ratio
# of diamonds. The variable x should be
# assigned to cut. The points should be colored
# by diamond color, and the plot should be
# faceted by clarity.

# The plot should look something like this.
# http://i.imgur.com/YzbWkHT.jpg.

# Note: In the link, a color palette of type
# 'div' was used to color the histogram using
# scale_color_brewer(type = 'div')
```{R}
ggplot(aes(x=cut, y=price), data = diamonds) + 
  geom_jitter(aes(color = color), alpha = 1/2) + 
  facet_wrap('clarity') + 
  scale_color_brewer(type = 'div')
```

2. 
```{R}

```

2. 
```{R}

```

2. 
```{R}

```